- project:
    check:
      jobs:
        - openstack-tox-pep8
        - networking-nuage-tempest-cli: &rocky
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
            required-projects:
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.9.0
              - name: openstack/nova
                override-checkout: rocky-eol
        - nuage-neutronclient-functional: *rocky
    gate:
      jobs:
        - openstack-tox-pep8
        - networking-nuage-tempest-cli: *rocky
        - nuage-neutronclient-functional: *rocky
    periodic:
      jobs:
        - nuage-neutronclient-functional: *rocky

