- project:
    check:
      jobs:
        - openstack-tox-pep8
        - networking-nuage-tempest-cli: &queens
            vars:
              devstack_localrc:
                USE_PYTHON3: false
                FORCE_CONFIG_DRIVE: false
            required-projects:
              - name: openstack/neutron-tempest-plugin
                override-checkout: 0.3.0
        - nuage-neutronclient-functional: *queens
    gate:
      jobs:
        - openstack-tox-pep8
        - networking-nuage-tempest-cli: *queens
        - nuage-neutronclient-functional: *queens
    periodic:
      jobs:
        - nuage-neutronclient-functional: *queens
