- project:
    check:
      jobs:
        - openstack-tox-pep8
        - networking-nuage-tempest-cli
        - nuage-neutronclient-functional
    gate:
      jobs:
        - openstack-tox-pep8
        - networking-nuage-tempest-cli
        - nuage-neutronclient-functional
    periodic:
      jobs:
        - nuage-neutronclient-functional
