- project:
    check:
      jobs:
        - openstack-tox-pep8
        - nuage-neutronclient-cli
        - nuage-neutronclient-functional: &queens
            override-checkout: stable/queens
            required-projects:
              - OpenStack/networking-testsriov
              - name: OpenStack/nuage-openstack-neutron
                override-checkout: 6.0/queens
              - name: OpenStack/nuage-openstack-neutronclient
                override-checkout: 6.0/queens
              - opendev.org/openstack/neutron
              - opendev.org/openstack/python-openstackclient
              - opendev.org/openstack/placement
            vars:
              vsp_release: '6.0'
              devstack_localrc:
                USE_PYTHON3: false
    gate:
      jobs:
        - openstack-tox-pep8
        - nuage-neutronclient-cli
        - nuage-neutronclient-functional: *queens
    periodic:
      jobs:
        - nuage-neutronclient-functional: *queens

- job:
    name: nuage-neutronclient-cli
    parent: networking-nuage-base
    nodeset: openstack-single-node-centos7
    override-checkout: stable/queens
    vars:
      vsp_release: '6.0'
      tempest_test_regex: '^nuage_tempest_plugin\.tests\.api\.cli\..*'
      devstack_localrc:
        TEMPEST_PLUGINS: '"/opt/stack/nuage-tempest-plugin"'
        Q_ML2_PLUGIN_TYPE_DRIVERS: vxlan,vlan,flat
      devstack_local_conf:
        test-config:
          $TEMPEST_CONFIG:
            nuage_sut:
              nuage_hybrid_mpls_enabled: False
    required-projects:
      - name: OpenStack/nuage-openstack-neutron
        override-checkout: 6.0/queens
      - name: OpenStack/nuage-openstack-neutronclient
        override-checkout: 6.0/queens
      - name: opendev.org/openstack/neutron-tempest-plugin
        override-checkout: 0.3.0
