- hosts: localhost
  roles:
    - role: set-nuage-vsp-facts

- hosts: all
  roles:
    - vsp-info
  tasks:
    - name: Workaround uwsgi 2.0.19
      lineinfile:
        path: /opt/stack/requirements/upper-constraints.txt
        line: uwsgi===2.0.18

    - name: Workaround bandit 1.6.3
      lineinfile:
        path: /opt/stack/requirements/upper-constraints.txt
        line: bandit===1.6.2
