- hosts: localhost
  roles:
    - role: set-nuage-vsp-facts

- hosts: all
  roles:
    - vsp-info
  tasks:
    # gridinv: 15.1.0 causes tempest install to fail
    - name: bump virtualenv to 16.7.10
      lineinfile:
        path: /opt/stack/requirements/upper-constraints.txt
        regexp: '^virtualenv==='
        line: 'virtualenv===16.7.10'
      when: zuul.branch | regex_search("^(5.4|6.0|stable)/queens$")

    - name: Workaround uwsgi 2.0.19
      lineinfile:
        path: /opt/stack/requirements/upper-constraints.txt
        line: uwsgi===2.0.18

    - name: Workaround bandit 1.6.3
      lineinfile:
        path: /opt/stack/requirements/upper-constraints.txt
        line: bandit===1.6.2
