- hosts: localhost
  tasks:
    - name: Set no_proxy fact
      set_fact:
        no_proxy: "{{ proxy_env['no_proxy'] }}"
      when: proxy_env is defined

    - name: compute no_proxy
      block:
      - set_fact:
          no_proxy: "{{ no_proxy }},{{ hostvars[item]['nodepool']['interface_ip'] }}"
        when:
          - proxy_env is defined
          - hostvars[item]['nodepool']['interface_ip'] is defined
        with_items: "{{ query('inventory_hostnames', 'all,!localhost') }}"

- hosts: controller
  tasks:
    - name: fetch vsp_info
      slurp:
        src: /etc/ci/vsp_info.yaml
      register: vsp_info

- hosts: all
  vars:
    vsp: "{{ hostvars['controller']['vsp_info']['content'] | b64decode | from_yaml}}"
    env:
      no_proxy: "{{ vsp['vsd_server'].split(':')[0]}},{{ hostvars['localhost']['no_proxy'] | default('') }}"
    devstack_localrc:
      NUAGE_VSD_SERVERS: "{{ vsp['vsd_server'] }}"
      NUAGE_VSC_SERVER: "{{ vsp['vsc_controller'] }}"
      NUAGE_VSP_RELEASE: "{{ vsp['nuage_vsp_release'] }}"
  roles:
    - setup-nuage-source-dirs
    - write-vsp-devstack-local-conf
    - run-devstack
    # Run bindep and test-setup after devstack so that they won't interfere
    - role: bindep
      bindep_profile: test
      bindep_dir: "{{ zuul_work_dir }}"
    - test-setup
    - ensure-tox
    - tox
  environment: '{{ proxy_env | default({}) | combine(env) }}'
